TrajectoryPlannerROS:
  meter_scoring: true
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true
  sim_time: 1.5
  sim_granularity: 0.025
  path_distance_bias: 32.0        # > giá trị cao → robot cố bám đường chính
  goal_distance_bias: 24.0        # > giá trị cao → robot thích đến đích sớm hơn
  obstacle_distance: 0.5
